# Generated by Django 2.2.5 on 2021-09-23 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('status', models.TextField(blank=True, max_length=100)),
                ('location', models.TextField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='pics')),
            ],
        ),
    ]
